// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "cpc_types.hpp"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// process_chromatogram
Rcpp::List process_chromatogram(vec_d& d0, vec_d& d1, vec_d& d2, double apex_thresh, int w, int p, double liftoff, double touchdown, int output);
RcppExport SEXP _cpc_process_chromatogram(SEXP d0SEXP, SEXP d1SEXP, SEXP d2SEXP, SEXP apex_threshSEXP, SEXP wSEXP, SEXP pSEXP, SEXP liftoffSEXP, SEXP touchdownSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< vec_d& >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< vec_d& >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< double >::type apex_thresh(apex_threshSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type liftoff(liftoffSEXP);
    Rcpp::traits::input_parameter< double >::type touchdown(touchdownSEXP);
    Rcpp::traits::input_parameter< int >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(process_chromatogram(d0, d1, d2, apex_thresh, w, p, liftoff, touchdown, output));
    return rcpp_result_gen;
END_RCPP
}
// c_emg_eval
double c_emg_eval(vec_d& pars, vec_d& x, vec_d& y, vec_d& w, int n);
RcppExport SEXP _cpc_c_emg_eval(SEXP parsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< vec_d& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emg_eval(pars, x, y, w, n));
    return rcpp_result_gen;
END_RCPP
}
// c_emg_eval2
double c_emg_eval2(vec_d& pars, vec_d& x, vec_d& y, vec_d& w, int n);
RcppExport SEXP _cpc_c_emg_eval2(SEXP parsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< vec_d& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emg_eval2(pars, x, y, w, n));
    return rcpp_result_gen;
END_RCPP
}
// c_emg_grad
vec_d c_emg_grad(vec_d& pars, vec_d& x, vec_d& y, vec_d& w, int n, double h);
RcppExport SEXP _cpc_c_emg_grad(SEXP parsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP nSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< vec_d& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emg_grad(pars, x, y, w, n, h));
    return rcpp_result_gen;
END_RCPP
}
// getEIC_min
vec_d getEIC_min(vec_d& mz, vec_d& intensity, vec_i& scan_idx, vec_d& mz_range, vec_i& scan_range);
RcppExport SEXP _cpc_getEIC_min(SEXP mzSEXP, SEXP intensitySEXP, SEXP scan_idxSEXP, SEXP mz_rangeSEXP, SEXP scan_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< vec_i& >::type scan_idx(scan_idxSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type mz_range(mz_rangeSEXP);
    Rcpp::traits::input_parameter< vec_i& >::type scan_range(scan_rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(getEIC_min(mz, intensity, scan_idx, mz_range, scan_range));
    return rcpp_result_gen;
END_RCPP
}
// getEIC_Rcpp
NumericVector getEIC_Rcpp(NumericVector& mz, NumericVector& intensity, IntegerVector& scan_idx, NumericVector& mz_range, IntegerVector& scan_range);
RcppExport SEXP _cpc_getEIC_Rcpp(SEXP mzSEXP, SEXP intensitySEXP, SEXP scan_idxSEXP, SEXP mz_rangeSEXP, SEXP scan_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type scan_idx(scan_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type mz_range(mz_rangeSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type scan_range(scan_rangeSEXP);
    rcpp_result_gen = Rcpp::wrap(getEIC_Rcpp(mz, intensity, scan_idx, mz_range, scan_range));
    return rcpp_result_gen;
END_RCPP
}
// fast_match
vec_i fast_match(vec_i& v1, vec_i& v2);
RcppExport SEXP _cpc_fast_match(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_i& >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< vec_i& >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(fast_match(v1, v2));
    return rcpp_result_gen;
END_RCPP
}
// match_to_range
vec_i match_to_range(vec_d& v, vec_d& vmin, vec_d& vmax);
RcppExport SEXP _cpc_match_to_range(SEXP vSEXP, SEXP vminSEXP, SEXP vmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type v(vSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type vmin(vminSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type vmax(vmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(match_to_range(v, vmin, vmax));
    return rcpp_result_gen;
END_RCPP
}
// skim_to_val
int skim_to_val(vec_d& v, double val, int start_at, int break_at, int direction);
RcppExport SEXP _cpc_skim_to_val(SEXP vSEXP, SEXP valSEXP, SEXP start_atSEXP, SEXP break_atSEXP, SEXP directionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type val(valSEXP);
    Rcpp::traits::input_parameter< int >::type start_at(start_atSEXP);
    Rcpp::traits::input_parameter< int >::type break_at(break_atSEXP);
    Rcpp::traits::input_parameter< int >::type direction(directionSEXP);
    rcpp_result_gen = Rcpp::wrap(skim_to_val(v, val, start_at, break_at, direction));
    return rcpp_result_gen;
END_RCPP
}
// c_integrate_vector
double c_integrate_vector(vec_d& x, vec_d& y, int a, int b);
RcppExport SEXP _cpc_c_integrate_vector(SEXP xSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(c_integrate_vector(x, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// c_run_mean
vec_d c_run_mean(vec_d& x, int b);
RcppExport SEXP _cpc_c_run_mean(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(c_run_mean(x, b));
    return rcpp_result_gen;
END_RCPP
}
// c_lm_fit
vec_d c_lm_fit(vec_d& x, vec_d& y, int a, int b);
RcppExport SEXP _cpc_c_lm_fit(SEXP xSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(c_lm_fit(x, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// c_lm_slope
double c_lm_slope(vec_d& x, vec_d& y, int a, int b);
RcppExport SEXP _cpc_c_lm_slope(SEXP xSEXP, SEXP ySEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(c_lm_slope(x, y, a, b));
    return rcpp_result_gen;
END_RCPP
}
// vector_residual
vec_d vector_residual(NumericVector& x, NumericVector& y);
RcppExport SEXP _cpc_vector_residual(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(vector_residual(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_local_extremes2
vec_i c_local_extremes2(vec_d& v, int w);
RcppExport SEXP _cpc_c_local_extremes2(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c_local_extremes2(v, w));
    return rcpp_result_gen;
END_RCPP
}
// c_local_extremes
vec_i c_local_extremes(vec_d& v, int w);
RcppExport SEXP _cpc_c_local_extremes(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c_local_extremes(v, w));
    return rcpp_result_gen;
END_RCPP
}
// c_peak_to_peak_noise
double c_peak_to_peak_noise(vec_i& x, vec_d& y, int w);
RcppExport SEXP _cpc_c_peak_to_peak_noise(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_i& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c_peak_to_peak_noise(x, y, w));
    return rcpp_result_gen;
END_RCPP
}
// c_running_slope
vec_d c_running_slope(vec_d& x, vec_d& y, int w);
RcppExport SEXP _cpc_c_running_slope(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c_running_slope(x, y, w));
    return rcpp_result_gen;
END_RCPP
}
// c_local_max
vec_i c_local_max(vec_d& v, int w);
RcppExport SEXP _cpc_c_local_max(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c_local_max(v, w));
    return rcpp_result_gen;
END_RCPP
}
// c_local_min
vec_i c_local_min(vec_d& v, int w);
RcppExport SEXP _cpc_c_local_min(SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c_local_min(v, w));
    return rcpp_result_gen;
END_RCPP
}
// c_get_inflection_points
vec_i c_get_inflection_points(vec_d& x, int b);
RcppExport SEXP _cpc_c_get_inflection_points(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(c_get_inflection_points(x, b));
    return rcpp_result_gen;
END_RCPP
}
// c_get_directional_inflection_points
vec_i c_get_directional_inflection_points(std::vector<double>& x, int b);
RcppExport SEXP _cpc_c_get_directional_inflection_points(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(c_get_directional_inflection_points(x, b));
    return rcpp_result_gen;
END_RCPP
}
// emgfun
vec_d emgfun(vec_d& x, vec_d& pars, unsigned int npeaks);
RcppExport SEXP _cpc_emgfun(SEXP xSEXP, SEXP parsSEXP, SEXP npeaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec_d& >::type x(xSEXP);
    Rcpp::traits::input_parameter< vec_d& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type npeaks(npeaksSEXP);
    rcpp_result_gen = Rcpp::wrap(emgfun(x, pars, npeaks));
    return rcpp_result_gen;
END_RCPP
}
// c_emgfit_bfgs
arma::vec c_emgfit_bfgs(arma::vec& si, arma::vec& st, arma::vec& wt, arma::vec seed, int np, bool hess, int trace, double h);
RcppExport SEXP _cpc_c_emgfit_bfgs(SEXP siSEXP, SEXP stSEXP, SEXP wtSEXP, SEXP seedSEXP, SEXP npSEXP, SEXP hessSEXP, SEXP traceSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< bool >::type hess(hessSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emgfit_bfgs(si, st, wt, seed, np, hess, trace, h));
    return rcpp_result_gen;
END_RCPP
}
// c_emgfit_lbfgsb
arma::vec c_emgfit_lbfgsb(arma::vec& si, arma::vec& st, arma::vec& wt, arma::vec seed, arma::vec lower, arma::vec upper, int np, bool hess, int trace, double h);
RcppExport SEXP _cpc_c_emgfit_lbfgsb(SEXP siSEXP, SEXP stSEXP, SEXP wtSEXP, SEXP seedSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP npSEXP, SEXP hessSEXP, SEXP traceSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< bool >::type hess(hessSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emgfit_lbfgsb(si, st, wt, seed, lower, upper, np, hess, trace, h));
    return rcpp_result_gen;
END_RCPP
}
// c_emgfit_nmead
arma::vec c_emgfit_nmead(arma::vec& si, arma::vec& st, arma::vec& wt, arma::vec seed, int np, bool hess, int trace, double h);
RcppExport SEXP _cpc_c_emgfit_nmead(SEXP siSEXP, SEXP stSEXP, SEXP wtSEXP, SEXP seedSEXP, SEXP npSEXP, SEXP hessSEXP, SEXP traceSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< bool >::type hess(hessSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emgfit_nmead(si, st, wt, seed, np, hess, trace, h));
    return rcpp_result_gen;
END_RCPP
}
// c_emgfit_sann
arma::vec c_emgfit_sann(arma::vec& si, arma::vec& st, arma::vec& wt, arma::vec seed, int np, bool hess, int trace, double h);
RcppExport SEXP _cpc_c_emgfit_sann(SEXP siSEXP, SEXP stSEXP, SEXP wtSEXP, SEXP seedSEXP, SEXP npSEXP, SEXP hessSEXP, SEXP traceSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< bool >::type hess(hessSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emgfit_sann(si, st, wt, seed, np, hess, trace, h));
    return rcpp_result_gen;
END_RCPP
}
// c_emgfit_cg
arma::vec c_emgfit_cg(arma::vec& si, arma::vec& st, arma::vec& wt, arma::vec seed, int np, bool hess, int trace, double h);
RcppExport SEXP _cpc_c_emgfit_cg(SEXP siSEXP, SEXP stSEXP, SEXP wtSEXP, SEXP seedSEXP, SEXP npSEXP, SEXP hessSEXP, SEXP traceSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< bool >::type hess(hessSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emgfit_cg(si, st, wt, seed, np, hess, trace, h));
    return rcpp_result_gen;
END_RCPP
}
// c_emgfit
arma::vec c_emgfit(arma::vec& si, arma::vec& st, arma::vec& wt, arma::vec seed, arma::vec lower, arma::vec upper, int np, bool hess, int trace, double h, const std::string method);
RcppExport SEXP _cpc_c_emgfit(SEXP siSEXP, SEXP stSEXP, SEXP wtSEXP, SEXP seedSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP npSEXP, SEXP hessSEXP, SEXP traceSEXP, SEXP hSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type si(siSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< bool >::type hess(hessSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(c_emgfit(si, st, wt, seed, lower, upper, np, hess, trace, h, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cpc_process_chromatogram", (DL_FUNC) &_cpc_process_chromatogram, 9},
    {"_cpc_c_emg_eval", (DL_FUNC) &_cpc_c_emg_eval, 5},
    {"_cpc_c_emg_eval2", (DL_FUNC) &_cpc_c_emg_eval2, 5},
    {"_cpc_c_emg_grad", (DL_FUNC) &_cpc_c_emg_grad, 6},
    {"_cpc_getEIC_min", (DL_FUNC) &_cpc_getEIC_min, 5},
    {"_cpc_getEIC_Rcpp", (DL_FUNC) &_cpc_getEIC_Rcpp, 5},
    {"_cpc_fast_match", (DL_FUNC) &_cpc_fast_match, 2},
    {"_cpc_match_to_range", (DL_FUNC) &_cpc_match_to_range, 3},
    {"_cpc_skim_to_val", (DL_FUNC) &_cpc_skim_to_val, 5},
    {"_cpc_c_integrate_vector", (DL_FUNC) &_cpc_c_integrate_vector, 4},
    {"_cpc_c_run_mean", (DL_FUNC) &_cpc_c_run_mean, 2},
    {"_cpc_c_lm_fit", (DL_FUNC) &_cpc_c_lm_fit, 4},
    {"_cpc_c_lm_slope", (DL_FUNC) &_cpc_c_lm_slope, 4},
    {"_cpc_vector_residual", (DL_FUNC) &_cpc_vector_residual, 2},
    {"_cpc_c_local_extremes2", (DL_FUNC) &_cpc_c_local_extremes2, 2},
    {"_cpc_c_local_extremes", (DL_FUNC) &_cpc_c_local_extremes, 2},
    {"_cpc_c_peak_to_peak_noise", (DL_FUNC) &_cpc_c_peak_to_peak_noise, 3},
    {"_cpc_c_running_slope", (DL_FUNC) &_cpc_c_running_slope, 3},
    {"_cpc_c_local_max", (DL_FUNC) &_cpc_c_local_max, 2},
    {"_cpc_c_local_min", (DL_FUNC) &_cpc_c_local_min, 2},
    {"_cpc_c_get_inflection_points", (DL_FUNC) &_cpc_c_get_inflection_points, 2},
    {"_cpc_c_get_directional_inflection_points", (DL_FUNC) &_cpc_c_get_directional_inflection_points, 2},
    {"_cpc_emgfun", (DL_FUNC) &_cpc_emgfun, 3},
    {"_cpc_c_emgfit_bfgs", (DL_FUNC) &_cpc_c_emgfit_bfgs, 8},
    {"_cpc_c_emgfit_lbfgsb", (DL_FUNC) &_cpc_c_emgfit_lbfgsb, 10},
    {"_cpc_c_emgfit_nmead", (DL_FUNC) &_cpc_c_emgfit_nmead, 8},
    {"_cpc_c_emgfit_sann", (DL_FUNC) &_cpc_c_emgfit_sann, 8},
    {"_cpc_c_emgfit_cg", (DL_FUNC) &_cpc_c_emgfit_cg, 8},
    {"_cpc_c_emgfit", (DL_FUNC) &_cpc_c_emgfit, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_cpc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
